logFilters:
  - code: YN0060
    level: error
  - code: YN0002
    level: error
  - level: discard
    pattern: "*gatsby* doesn't provide"
  - level: discard
    pattern: "@monodeploy/gatsby@workspace:gatsby provides react"
  - level: discard
    pattern: "lists build scripts, but its build has been explicitly disabled through configuration"

npmRegistries:
  //registry.npmjs.org/:
    npmAuthToken: "${NPM_PUBLISH_TOKEN:-invalid}"

packageExtensions:
  "@cspotcode/source-map-support@*":
    dependencies:
      source-map-support: "*"
  "@mdx-js/loader@*":
    peerDependencies:
      react: ^17.0.0
  "@parcel/types@*":
    peerDependencies:
      "@parcel/core": "*"
    peerDependenciesMeta:
      "@parcel/core":
        optional: true
  react-dev-utils@*:
    peerDependenciesMeta:
      webpack:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-semver-up.cjs
    spec: "https://raw.githubusercontent.com/tophat/yarn-plugin-semver-up/master/bundles/%40yarnpkg/plugin-semver-up.js"
