npmRegistries:
  //registry.npmjs.org/:
    npmAuthToken: "${NPM_PUBLISH_TOKEN:-invalid}"

packageExtensions:
  "@tophat/conventional-changelog-config@0.0.9":
    dependencies:
      compare-func: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-sources.cjs
