compressionLevel: mixed

logFilters:
  - code: YN0060
    level: error
  - code: YN0002
    level: error
  - level: discard
    pattern: "*gatsby* doesn't provide"
  - level: discard
    pattern: "@monodeploy/gatsby@workspace:gatsby provides react"
  - level: discard
    pattern: "lists build scripts, but its build has been explicitly disabled through configuration"
  - level: discard
    pattern: "react is listed by your project with version 18.2.0, which doesn't satisfy what gatsby"

npmRegistries:
  //registry.npmjs.org/:
    npmAuthToken: "${NPM_PUBLISH_TOKEN:-invalid}"

packageExtensions:
  "@parcel/types@*":
    peerDependencies:
      "@parcel/core": "*"
    peerDependenciesMeta:
      "@parcel/core":
        optional: true
  react-dev-utils@*:
    peerDependenciesMeta:
      webpack:
        optional: true
