version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "chore"
    ignored_updates:
      - match:
          dependency_name: lerna
          version_requirement: "> 3.15.0"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "in_range"
