version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "chore"
  - package_manager: "javascript"
    directory: "/website"
    update_schedule: "weekly"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "chore"
