name: Master Branch

on:
  - push

env:
  CI: 1
  ARTIFACT_DIR: ./artifacts

jobs:
  tests:
    name: Lint, Tests, and Build
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    steps:
        - uses: actions/checkout@v2
        - uses: ./.github/actions/detect-node
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: ${{ env.NODE_VERSION }}
        - name: Create artifacts directory
          run: mkdir -p ${{ env.ARTIFACT_DIR }}
        - name: Restore yarn cache
          id: yarn-cache
          uses: actions/cache@v2
          with:
            path: ./.yarn/cache
            key: ${{ env.NODE_VERSION }}-${{ env.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}
        - name: Install dependencies
          run: yarn install --immutable
        - name: Linting
          run: yarn lint:ci
        - name: Tests
          run: yarn test:ci
        - name: Upload Coverage Report
          run: ./.github/codecov.sh $GITHUB_EVENT_PATH
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        - name: Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: reports-and-build-artifacts
            path: ${{ env.ARTIFACT_DIR }}
