name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: 1
  ARTIFACT_DIR: ./artifacts

jobs:
  tests_compatibility_1:
    name: Test Compatibility - 1
    runs-on: ${{ matrix.runner}}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        runner: ['ubuntu-latest']
        node-version: ['lts/iron']
      fail-fast: false
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
        with:
          node-version: ${{ matrix.node-version }}
          cache-prefix: ${{ matrix.runner }}
      - name: Build
        run: yarn build
      - name: Set GitHub user for tests
        run: |
          git config --global user.email "opensource@tophat.com"
          git config --global user.name "Top Hat Open Source"
          git config --global init.defaultBranch main
      - name: Tests
        run: >-
          yarn test:ci --verbose
