name: Release

on:
  workflow_dispatch:

env:
  CI: 1
  ARTIFACT_DIR: ./artifacts

jobs:
  pre-release-check:
    name: Publish Monodeploy (Precheck)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          token: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      - name: Build
        run: yarn build
      - name: Configure Git
        run: |
          git config --global user.name tophat-opensource-bot
          git config --global user.email opensource-leads+bot@tophatmonocle.com
          git config --global init.defaultBranch main
      - name: Tests
        run: yarn test:ci

  release:
    name: Publish Monodeploy
    runs-on: ubuntu-latest
    needs: [pre-release-check]
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          token: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      - name: Build
        run: yarn build
      - name: Publish via Monodeploy (Pre-release)
        if: github.ref != 'refs/heads/main'
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GH_TOKEN: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
        run: |
          yarn run-local \
            --log-level 0 \
            --conventional-changelog-config @tophat/conventional-changelog-config \
            --push \
            --changeset-ignore-patterns '**/*.test.ts' \
            --prerelease \
            --package-group-manifest-field group
      - name: Publish via Monodeploy
        if: github.ref == 'refs/heads/main'
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GH_TOKEN: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
        run: |
          yarn run-local \
            --log-level 0 \
            --conventional-changelog-config @tophat/conventional-changelog-config \
            --changelog-filename "<packageDir>/CHANGELOG.md" \
            --persist-versions \
            --auto-commit \
            --auto-commit-message "chore: release monodeploy [skip ci]" \
            --plugins "@monodeploy/plugin-github" \
            --push \
            --changeset-ignore-patterns '**/*.test.ts' \
            --package-group-manifest-field group
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ${{ env.ARTIFACT_DIR }}
