name: Release

on:
  push:
    tags:
      - "v*"

env:
  CI: 1
  ARTIFACT_DIR: ./artifacts

jobs:
  release:
    name: Publish Commit Watch
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v2
        - uses: ./.github/actions/detect-node
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: ${{ env.NODE_VERSION }}
        - name: Create artifacts directory
          run: mkdir -p ${{ env.ARTIFACT_DIR }}
        - name: Restore yarn cache
          id: yarn-cache
          uses: actions/cache@v2
          with:
            path: ./.yarn/cache
            key: ${{ env.NODE_VERSION }}-${{ env.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}
        - name: Install dependencies
          run: yarn install --immutable
        - name: Build Package
          run: yarn build
        - name: Set Publish Credentials
          env:
            NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          run: |
            npm config set registry=https://registry.npmjs.org/
            npm config set "//registry.npmjs.org/:_authToken" "${NPM_PUBLISH_TOKEN}"
        - name: Publish Package
          run: yarn deploy
        - name: Upload Artifacts
          if: ${{ always() }}
          uses: actions/upload-artifact@v2
          with:
            name: reports-and-build-artifacts
            path: |
                ${{ env.ARTIFACT_DIR }}
                ~/.npm/_logs/*.log
