name: Release

on:
  workflow_dispatch:

env:
  CI: 1
  ARTIFACT_DIR: ./artifacts

jobs:
  release:
    name: Publish Monodeploy
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
          with:
            token: ${{ secrets.GH_TOKEN }}
        - uses: ./.github/actions/detect-env
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: ${{ env.NODE_VERSION }}
        - name: Create artifacts directory
          run: mkdir -p ${{ env.ARTIFACT_DIR }}
        - name: Restore yarn cache
          id: yarn-cache
          uses: actions/cache@v2
          with:
            path: |
              ./.yarn
              .pnp.*
            key: ${{ env.NODE_VERSION }}-${{ env.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}
        - name: Install dependencies
          run: |
            yarn install --immutable
            cd example-monorepo && yarn
        - name: Build
          run: yarn build
        - name: Configure Git
          run: |
            git config user.name tophat-opensource-bot
            git config user.email opensource-leads+bot@tophatmonocle.com
        - name: Tests
          run: yarn test:ci
        - name: Publish via Monodeploy (Dry Run)
          if: github.ref != 'refs/heads/master'
          run: |
            yarn node ./packages/cli/lib/cli.js \
              --dry-run \
              --log-level 0 \
              --conventional-changelog-config @tophat/conventional-changelog-config \
              --prepend-changelog ./CHANGELOG.md
            git status
            git --no-pager diff
        - name: Publish via Monodeploy
          if: github.ref == 'refs/heads/master'
          env:
            NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          run: |
            yarn node ./packages/cli/lib/cli.js \
              --log-level 0 \
              --conventional-changelog-config @tophat/conventional-changelog-config \
              --prepend-changelog ./CHANGELOG.md \
              --persist-versions
        - name: Update Git Repository
          if: github.ref == 'refs/heads/master'
          run: |
            git status
            git --no-pager diff
